name: Terraform Deployment

on:
  push:
    branches:
      - main 

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  TF_VAR_ADMIN_ROLE: ${{ vars.TF_VAR_ADMIN_ROLE}}
  TF_VAR_DEVELOPER_ROLE: ${{ vars.TF_VAR_DEVELOPER_ROLE}}

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }} # use github env
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }} # use github env

      - name: Terraform Init
        run: terraform init -var="user_for_admin_role=${{ env.TF_VAR_ADMIN_ROLE }}" -var="user_for_dev_role=${{ env.TF_VAR_DEVELOPER_ROLE }}"

      - name: Upload Terraform Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-artifacts
          path: |
            .terraform/
            .terraform.lock.hcl

      - name: Terraform Plan
        run: terraform plan -var="user_for_admin_role=${{ env.TF_VAR_ADMIN_ROLE }}" -var="user_for_dev_role=${{ env.TF_VAR_DEVELOPER_ROLE }}" -out "planfile"

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: planfile

#   deploy:
#     runs-on: ubuntu-latest
#     permissions:
#         id-token: write
#         contents: read
#     needs: plan
#     environment: production # or your environment
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.9

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#             role-to-assume: ${{ env.ROLE_ARN }}
#             role-session-name: GitHubActions-${{ github.run_id }}
#             aws-region: ${{ env.AWS_REGION }}

#       - name: Terraform Init
#         run: terraform init -var="user_for_admin_role=${{ env.TF_VAR_ADMIN_ROLE }}" -var="user_for_dev_role=${{ env.TF_VAR_DEVELOPER_ROLE }}"
  
#     #   - name: Download Terraform Artifacts
#     #     uses: actions/download-artifact@v4
#     #     with:
#     #       name: terraform-artifacts

#       - name: Download Terraform Plan Artifacts
#         uses: actions/download-artifact@v4
#         with:
#           name: terraform-plan

#       - name: Terraform Apply
#         run: terraform apply -input=false "planfile"

  cleanup:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    needs: plan
    environment: production # or your environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ env.ROLE_ARN }}
            role-session-name: GitHubActions-${{ github.run_id }}
            aws-region: ${{ env.AWS_REGION }}
            
      - name: Terraform Init
        run: terraform init -var="user_for_admin_role=${{ env.TF_VAR_ADMIN_ROLE }}" -var="user_for_dev_role=${{ env.TF_VAR_DEVELOPER_ROLE }}"
              
    #   - name: Download Terraform Artifacts
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: terraform-artifacts

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="user_for_admin_role=${{ env.TF_VAR_ADMIN_ROLE }}" -var="user_for_dev_role=${{ env.TF_VAR_DEVELOPER_ROLE }}"
