name: Terraform Deployment

on:
  push:
    branches:
      - main 
  pull_request:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }} # use github env
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }} # use github env

      - name: Terraform Init
        run: terraform init

      - name: Upload Terraform Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-artifacts
          path: |
            .terraform/
            .terraform.lock.hcl

  build:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    needs: init
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9

      - name: Download Terraform Artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform-artifacts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan
        run: terraform plan -out "planfile"

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: planfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    needs: build
    environment: production # or your environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9

      - name: Download Terraform Artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform-artifacts

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Apply
        run: terraform apply -input=false "planfile"

  cleanup:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    needs: deploy
    if: github.event_name == 'push' # Only on push events. you can change the condition
    environment: production # or your environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9

      - name: Download Terraform Artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform-artifacts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: GitHubActions-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve